[telegram]
token = "5978321932:AAFJHnuW0i-YFT9Nh2PJl0-Casc2rCz09TA"
workers = 1
admins = [737737727]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[pyrogram]
enabled = true
api_id = 4954361
api_hash = "43a786a8548a30f9d6887e36d53c0e64"

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = ""
issues = ""
channel = "botssaved"
